routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth'], function () {
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
Route::get('/add-email', [App\Http\Controllers\EmailController::class, 'addEmail'])->name('addEmail');
Route::post('/save-email', [App\Http\Controllers\EmailController::class, 'storeEmail'])->name('storeEmail');
Route::get('/email', [App\Http\Controllers\EmailController::class, 'listEmail'])->name('listEmail');
//Employee
 Route::resource('employee', \App\Http\Controllers\EmployeeController::class);

//leave
Route::get('/add-leave', [App\Http\Controllers\LeaveController::class, 'addLeave'])->name('addLeave');
Route::post('/save-leave', [App\Http\Controllers\LeaveController::class, 'storeLeave'])->name('storeLeave');
Route::get('/my-leave', [App\Http\Controllers\LeaveController::class, 'myLeave'])->name('myLeave');
Route::get('/leave-list', [App\Http\Controllers\LeaveController::class, 'listLeave'])->name('listLeave');
Route::get('/reply-to-user/{id}', [App\Http\Controllers\LeaveController::class, 'replyTouser'])->name('replyTouser');
Route::post('/reply-to-store', [App\Http\Controllers\LeaveController::class, 'replyToStore'])->name('replyToStore');
Route::post('/delete-leave', [App\Http\Controllers\LeaveController::class, 'deleteLeave'])->name('deleteLeave');
});

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\User;
use Auth;


class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('employee.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('employee.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
              $input = $request->all(); 
              $input['password'] = bcrypt('123456');
              if(User::create($input)){
                return redirect()->route('employee.index')->with('success','Employee added successfully.');
              }

            } catch(\Illuminate\Database\QueryException $ex){
                dd($ex->getMessage());
              
            } 
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user,$id)
    {
        $useredit = $user->where('id',$id)->first();
        return view('employee.edit',compact('useredit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,User $user, $id)
    {
        $request->validate([
            'email' => 'required|unique:users,email,'.$id,
        ]);

        try{
            $user = $user->where('id',$id)->first();
            $user->update($request->all());
            return redirect()->route('employee.index')->with('success', 'employee updated successfully');
        } catch (\Exception $e) {
            dd($e->getMessage());
            return redirect()->route('employee.index')->with('error',$e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user,$id)
    {
        $user->destroy($id);
        return redirect()->route('employee.index')->with('success','Employee deleted successfully');
    }
}

resources/views/employee/create.blade.php
@extends('layouts.dashboard_layout')

@section('content')
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Add Employee</h4>
                </div>
            </div>
        </div>
        <div class="container-fluid">
          @include('flash-message')
            <div class="row">
                <div class="col-lg-12 col-xlg-9 col-md-12">
                    <div class="card">
                        <div class="card-body">

                            <form class="form-horizontal form-material" method="post" id="add_email" action="{{route('employee.store')}}">
                              @csrf
                              <input type="hidden" name="sender_email" value="{{Auth::user()->email}}">
                                <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                                <input type="hidden" name="name" value="{{Auth::user()->name}}">
                                <input type="hidden" name="status" value="Pending">
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Name</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input  name="name" type="text" placeholder="Enter your name" class="form-control p-0 border-0" required> 
                                        </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Email</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input   name="email" type="email" placeholder="Enter your email address" class="form-control p-0 border-0" required> 
                                        </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-sm-12 p-0">Select Designation</label>

                                    <div class="col-sm-12 border-bottom">
                                        <select name="role"class="form-select shadow-none p-0 border-0 form-control-line" required>
                                            <option value="Team Leader">Team Leader</option>
                                            <option value="Employee">Employee</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-sm-12 p-0">Select Department</label>

                                    <div class="col-sm-12 border-bottom">
                                        <select name="department"class="form-select shadow-none p-0 border-0 form-control-line" required>
                                          <option value="Frontend Js">Frontend Js</option>
                                          <option value="Php">Php</option>
                                          <option value="Marketing">Marketing</option>
                                          <option value="Python">Python</option>
                                          <option value="QA">QA</option>

                                        </select>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <div class="col-sm-12">
                                        <button type="submit" class="btn btn-success">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.dashboard_layout')

@section('content')
        <div class="page-breadcrumb bg-white">
            <div class="row align-items-center">
                <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                    <h4 class="page-title">Add Employee</h4>
                </div>
            </div>
        </div>
        <div class="container-fluid">
          @include('flash-message')
            <div class="row">
                <div class="col-lg-12 col-xlg-9 col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form class="form-horizontal form-material" method="post" id="add_email" action="{{route('employee.update',$useredit->id)}}">
                              @csrf
                              @method('PUT')
                              {{-- <input type="hidden" name="sender_email" value="{{Auth::user()->email}}"> --}}
                                <input type="hidden" name="id" value="{{$useredit->id}}">
                                {{-- <input type="hidden" name="name" value="{{Auth::user()->name}}"> --}}
                                {{-- <input type="hidden" name="status" value="Pending"> --}}
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Name</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input   name="name" type="text" placeholder="Enter your name" class="form-control p-0 border-0" value="{{$useredit->name}}" required> 
                                        </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-md-12 p-0">Email</label>
                                        <div class="col-md-12 border-bottom p-0">
                                            <input   name="email" type="email" placeholder="Enter your email address" class="form-control p-0 border-0" value="{{$useredit->email}}" required> 
                                        </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-sm-12 p-0">Select Designation</label>

                                    <div class="col-sm-12 border-bottom">
                                        <select name="role"class="form-select shadow-none p-0 border-0 form-control-line" value="{{$useredit->leave_type}}" required>
                                            <option value="Team Leader">Team Leader</option>
                                            <option value="Employee">Employee</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <label class="col-sm-12 p-0">Select Department</label>
                                    <div class="col-sm-12 border-bottom">
                                        <select name="department"class="form-select shadow-none p-0 border-0 form-control-line"  value="{{$useredit->department}}" required>
                                          <option value="Frontend Js">Frontend Js</option>
                                          <option value="Php">Php</option>
                                          <option value="Marketing">Marketing</option>
                                          <option value="Python">Python</option>
                                          <option value="QA">QA</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group mb-4">
                                    <div class="col-sm-12">
                                        <button type="submit" class="btn btn-success">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/employee/index.blade.php
@extends('layouts.dashboard_layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-11 margin-tb">
             <div class="mx-auto md-8" id="btn_create">
                <a class="btn btn-success" href="{{ route('employee.create') }}"> Create</a>
            </div>
            <div class="pull-left">
                <h2>Employees List</h2>
            </div> 
        </div>
    </div>
    <table class=" col-lg-11 table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Department</th>
            <th>Action</th>
        </tr>
        @foreach ($users as $user)
        <tr>
            <td>{{ $user->id }}</td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->role }}</td>
            <td>{{ $user->department }}</td>
            <td>
                <form action="{{ route('employee.destroy',$user->id) }}" method="POST" onsubmit="return confirm('Are you sure want to delete ?')">
                        @csrf
                        @method('DELETE')
                        <a class="btn btn-primary btn-bg" href="{{ route('employee.edit',$user->id) }}">Edit</a>
                        <button type="submit" class="btn btn-danger">Delete</button>
                </form> 
            </td>
        </tr>
        @endforeach 
    </table>      
@endsection