routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => 'auth'], function () {
Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
Route::get('/add-email', [App\Http\Controllers\EmailController::class, 'addEmail'])->name('addEmail');
Route::post('/save-email', [App\Http\Controllers\EmailController::class, 'storeEmail'])->name('storeEmail');
Route::get('/email', [App\Http\Controllers\EmailController::class, 'listEmail'])->name('listEmail');
//Employee
 Route::resource('employee', \App\Http\Controllers\EmployeeController::class);

//leave
Route::get('/add-leave', [App\Http\Controllers\LeaveController::class, 'addLeave'])->name('addLeave');
Route::post('/save-leave', [App\Http\Controllers\LeaveController::class, 'storeLeave'])->name('storeLeave');
Route::get('/my-leave', [App\Http\Controllers\LeaveController::class, 'myLeave'])->name('myLeave');
Route::get('/leave-list', [App\Http\Controllers\LeaveController::class, 'listLeave'])->name('listLeave');
Route::get('/reply-to-user/{id}', [App\Http\Controllers\LeaveController::class, 'replyTouser'])->name('replyTouser');
Route::post('/reply-to-store', [App\Http\Controllers\LeaveController::class, 'replyToStore'])->name('replyToStore');
Route::post('/delete-leave', [App\Http\Controllers\LeaveController::class, 'deleteLeave'])->name('deleteLeave');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/dashboard_layout.blade.php
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
  <link href="{{ url('css/style.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url('css/custom.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{{ url('css/chosen/style.css') }}">
  <link rel="stylesheet" href="{{ url('css/chosen/chosen.css') }}">
</head>
<body>
   <div id="main-wrapper" data-layout="vertical" data-navbarbg="skin5" data-sidebartype="full"
       data-sidebar-position="absolute" data-header-position="absolute" data-boxed-layout="full">
       @include('layouts.header')
       @include('layouts.sidebar')
       <div class="page-wrapper" style="min-height: 250px;">
           @yield('content')
         </div>
   </div>
@include('layouts.footer')
</body>
</html>

resources/views/layouts/footer.blade.php
<script src="{{ url('js/jquery.js') }}" ></script>
<script src="{{ url('js/chosen/chosen.jquery.js') }}" ></script>
<script src="{{ url('js/chosen/init.js') }}" ></script>
<script src="{{ url('js/jquery.validate.js') }}" ></script>
<script src="{{ url('js/custom.js') }}" ></script>

resources/views/layouts/header.blade.php
<header class="topbar" data-navbarbg="skin5">
    <nav class="navbar top-navbar navbar-expand-md navbar-dark">
        <div class="navbar-header" data-logobg="skin6">
            <a class="navbar-brand" href="">
                    <img src="/images/zestGeek.svg" alt="homepage" width="200px" height="50px" />
                <span class="logo-text">
                    <!-- dark Logo text -->
                    <img src="plugins/images/logo-text.png" alt="homepage" />
                </span>
            </a>
            <a class="nav-toggler waves-effect waves-light text-dark d-block d-md-none"
                href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
        </div>
        <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
            <ul class="navbar-nav ms-auto d-flex align-items-center">
                <li>
                    <a href="#" class="dropdown-item" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
						<span class="font-medium logout-btn">  {{ __('Logout') }}</span>
						<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
							@csrf
						</form>
    				</a>
                </li>  
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/login_layout.blade.php
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
  <link rel="dns-prefetch" href="https://fonts.googleapis.com">
  <style>
  .main-content{
  	width: 50%;
  	border-radius: 20px;
  	box-shadow: 0 5px 5px rgba(0,0,0,.4);
  	margin: 5em auto;
  	display: flex;
  }
  .company__info{
  	background-color: #008080;
  	border-top-left-radius: 20px;
  	border-bottom-left-radius: 20px;
  	display: flex;
  	flex-direction: column;
  	justify-content: center;
  	color: #fff;
  }
  .fa-android{
  	font-size:3em;
  }
  @media screen and (max-width: 640px) {
  	.main-content{width: 90%;}
  	.company__info{
  		display: none;
  	}
  	.login_form{
  		border-top-left-radius:20px;
  		border-bottom-left-radius:20px;
  	}
  }
  @media screen and (min-width: 642px) and (max-width:800px){
  	.main-content{width: 70%;}
  }
  .row > h2{
  	color:#008080;
  }
  .login_form{
  	background-color: #fff;
  	border-top-right-radius:20px;
  	border-bottom-right-radius:20px;
  	border-top:1px solid #ccc;
  	border-right:1px solid #ccc;
  }
  form{
  	padding: 0 2em;
  }
  .form__input{
  	width: 100%;
  	border:0px solid transparent;
  	border-radius: 0;
  	border-bottom: 1px solid #aaa;
  	padding: 1em .5em .5em;
  	padding-left: 2em;
  	outline:none;
  	margin:1.5em auto;
  	transition: all .5s ease;
  }
  .form__input:focus{
  	border-bottom-color: #008080;
  	box-shadow: 0 0 5px rgba(0,80,80,.4);
  	border-radius: 4px;
  }
  .btn{
  	transition: all .5s ease;
  	width: 70%;
  	border-radius: 30px;
  	color:#008080;
  	font-weight: 600;
  	background-color: #fff;
  	border: 1px solid #008080;
  	margin-top: 1.5em;
  	margin-bottom: 1em;
  }
  .btn:hover, .btn:focus{
  	background-color: #008080;
  	color:#fff;
  }
  </style>

</head>
<body>


   <div class="container-fluid">
           @yield('content')
   </div>


</body>
</html>

resources/views/layouts/sidebar.blade.php
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <!-- User Profile-->
                @php
                $actual_link = $_SERVER['REQUEST_URI'];
					$link=substr($actual_link, strrpos($actual_link, '/') + 1);

                @endphp
                <li class="text-center p-20 upgrade-btn">

                    <a href="{{route('dashboard')}}"
                        class="btn d-grid {{($link=='dashboard')?'active':''}}" target="_blank">
                        Dashboard</a>
                </li>
                @if(Auth::user()->role=='user')
                <li class="text-center p-20 upgrade-btn ">
                    <a class="btn d-grid {{($link=='add-leave')?'active':''}}" href="{{route('addLeave')}}"
                        aria-expanded="false">
                        Add leave
                    </a>
                </li>
                @endif
                @if(Auth::user()->role=='user')
                <li class="text-center p-20 upgrade-btn">

                    <a href="{{route('myLeave')}}"
                        class="btn d-grid {{($link=='my-leave')?'active':''}}" target="_blank">
                        My leave</a>
                </li>
                @endif
                @if(Auth::user()->role=='admin')
                {{-- <li class="text-center p-20 upgrade-btn">

                        <a href="{{route('addEmail')}}"
                            class="btn d-grid {{($link=='add-email')?'active':''}}" target="_blank">
                            Add Reciever Email</a>

                </li> --}}
                {{-- <li class="text-center p-20 upgrade-btn">

                    <a href="{{route('listLeave')}}"
                        class="btn d-grid {{($link=='leave-list')?'active':''}}" target="_blank">
                        Leave List</a>

                </li> --}}
                {{-- <li class="text-center p-20 upgrade-btn">

                    <a href="{{route('listEmail')}}"
                        class="btn d-grid {{($link=='email')?'active':''}}" target="_blank">
                        List Email</a>

                </li> --}}
                <li class="text-center p-20 upgrade-btn">

                        <a href="{{route('employee.index')}}"
                            class="btn d-grid">
                            Add Employee</a>

                </li>
                @endif

                <!-- <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="profile.html"
                        aria-expanded="false">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span class="hide-menu">Profile</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="basic-table.html"
                        aria-expanded="false">
                        <i class="fa fa-table" aria-hidden="true"></i>
                        <span class="hide-menu">Basic Table</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="fontawesome.html"
                        aria-expanded="false">
                        <i class="fa fa-font" aria-hidden="true"></i>
                        <span class="hide-menu">Icon</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="map-google.html"
                        aria-expanded="false">
                        <i class="fa fa-globe" aria-hidden="true"></i>
                        <span class="hide-menu">Google Map</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="blank.html"
                        aria-expanded="false">
                        <i class="fa fa-columns" aria-hidden="true"></i>
                        <span class="hide-menu">Blank Page</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="404.html"
                        aria-expanded="false">
                        <i class="fa fa-info-circle" aria-hidden="true"></i>
                        <span class="hide-menu">Error 404</span>
                    </a>
                </li> -->
                <!-- <li class="text-center p-20 upgrade-btn">
                    <a href="https://www.wrappixel.com/templates/ampleadmin/"
                        class="btn d-grid btn-danger text-white" target="_blank">
                        Upgrade to Pro</a>
                </li> -->
            </ul>

        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>